### ISSUE TITLE
The gui interface displays very small fonts

### ISSUE THREAD

**Issue by b606** [flathub/org.scilab.Scilab#23]
Hi,

I tested Scilab from the flatpak and I ran into this problem:

The texts of the gui are almost unreadable while the preferences dialog shows Monospaced 13pt and 15pt.
(The console is OK). My system is a debian 12 with KDE plasma/X11 session.

I have the same problem for the flatpak version (2023.0.0) and the package from debian 12 version 6.1.1+dfsg2-6 (KDE plasma/X11 session).

Setting the configuration of gtk applications to "kde-gtk/Breeze" or 'Adwaita' does not solve the problem.

![Screenshot_20230712_Scilab_flatpak](https://github.com/flathub/org.scilab.Scilab/assets/7627533/8195a169-1899-4499-b882-1415d3c0058a)

**Expected result:**
- display fonts correctly: 
- should at least use the font size from the system as default (compare with the text of the window titles)

Additionally, it is impossible to open the preferences dialog on the debian 12 version (java crashed with an exception).

---
`flatpak info org.scilab.Scilab`

          ID: org.scilab.Scilab
         Ref: app/org.scilab.Scilab/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2023.0.0
     License: CECILL-2.1 or GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 637,0 Mo
     Runtime: org.freedesktop.Sdk/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 97df7f05645bd24d922f03ef92ba4c940fb7526d5748820f7b285469a58ffa…
      Parent: 2c48e562dd7dae0bdcb0fa7cd4068fc172fb64584c89b70dffbd6f381fb3e5…
     Subject: Update ncurses-6.4-20230617.tgz to 6.4-20230708 (996accc7)
        Date: 2023-07-09 17:17:55 +0000
---
`flatpak list`
```
Name                        Application ID                                 Version       Branch      Installation
Freedesktop Platform        org.freedesktop.Platform                       21.08.19      21.08       system
Freedesktop Platform        org.freedesktop.Platform                       22.08.12.1    22.08       system
Mesa                        org.freedesktop.Platform.GL.default            21.3.9        21.08       system
Mesa                        org.freedesktop.Platform.GL.default            23.1.1        22.08       system
Mesa (Extra)                org.freedesktop.Platform.GL.default            23.1.1        22.08-extra system
nvidia-470-182-03           org.freedesktop.Platform.GL.nvidia-470-182-03                1.4         system
openh264                    org.freedesktop.Platform.openh264              2.1.0         2.0         system
openh264                    org.freedesktop.Platform.openh264              2.1.0         2.2.0       system
Freedesktop SDK             org.freedesktop.Sdk                            22.08.12.1    22.08       system
Breeze GTK theme            org.gtk.Gtk3theme.Breeze                       5.27.6        3.22        system
KDE Application Platform    org.kde.Platform                                             5.15-21.08  system
KDE Application Platform    org.kde.Platform                                             5.15-22.08  system
Scilab                      org.scilab.Scilab                              2023.0.0      stable      system
```
plus few other applications.

---
**All system packages are from http://deb.debian.org/debian bookworm/main amd64 Packages**

`apt policy scilab flatpak breeze-gtk-theme gnome-themes-extra`
scilab: Installé : 6.1.1+dfsg2-6
flatpak: Installé : 1.14.4-1
breeze-gtk-theme: Installé : 5.27.5-2
gnome-themes-extra: Installé : 3.28-2 (for adwaita)

**Comment by kevinsmia1939** [comment]
Can you run `flatpak install scilab` and show me the error when opening preference dialog?
Did you use NVIDIA card? If so have you tried update all the flatpak? `flatpak update`

**Comment by b606** [comment]
Scilab does not crash with the flatpak org.scilab.Scilab but with `scilab: deb.debian.org : 6.1.1+dfsg2-6`

- The error message is 
```
Could not load file: /usr/share/scilab//modules/preferences/src/xslt/XConfiguration.xsl
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: java.lang.NullPointerException: Cannot invoke "javax.xml.transform.Transformer.transform(javax.xml.transform.Source, javax.xml.transform.Result)" because "org.scilab.modules.preferences.XCommonManager.transformer" is null

```
- All the packages are up to date.
- I have two "XConfiguration.xml" in $HOME/.Scilab
`user@n:~$ find .Scilab -name "XConfiguration.xml"` 
.Scilab/scilab-2023.1.0/XConfiguration.xml
.Scilab/scilab-branch-6.1/XConfiguration.xml

- I am using the proprietary NVidia driver on an old card (`nvidia-tesla-470-driver: 470.182.03-1`)
- The installation `flatpak install org.scilab.Scilab` automatically pulls in `org.freedesktop.Platform.GL.nvidia-470-182-03` and org.freedesktop.Platform.openh264

---
Complete session:

`user@n:~$ scilab`
Picked up _JAVA_OPTIONS: -Djava.class.path=/usr/share/java/flexdock.jar:/usr/share/java/skinlf.jar:/usr/share/java/looks.jar:/usr/share/java/commons-logging.jar:/usr/share/java/jhall.jar:/usr/share/java/lucene-core-4.10.4.jar:/usr/share/java/lucene-analyzers-common-4.10.4.jar:/usr/share/java/lucene-queryparser-4.10.4.jar:/usr/share/maven-repo/org/freehep/freehep-util/debian/freehep-util-debian.jar:/usr/share/maven-repo/org/freehep/freehep-io/debian/freehep-io-debian.jar:/usr/share/maven-repo/org/freehep/freehep-graphicsio/debian/freehep-graphicsio-debian.jar:/usr/share/java/freehep-graphicsio-emf.jar:/usr/share/java/freehep-graphics2d.jar:/usr/share/java/jrosetta-API.jar:/usr/share/java/jrosetta-engine.jar:/usr/share/java/jgraphx.jar:/usr/share/java/jogl2.jar:/usr/share/java/gluegen2-rt.jar:/usr/share/java/jeuclid-core.jar:/usr/share/java/jlatexmath-fop.jar:/usr/share/java/fop.jar:/usr/share/java/saxon.jar:/usr/share/java/batik.jar:/usr/share/java/xml-apis-ext.jar:/usr/share/java/commons-io.jar:/usr/share/java/xmlgraphics-commons.jar:/usr/share/java/avalon-framework.jar:/usr/share/java/jlatexmath.jar:/usr/share/java/ecj.jar:/usr/share/java/javax.activation.jar:/usr/share/java/jaxb-runtime.jar:/usr/share/scilab/modules/graph/jar/org.scilab.modules.graph.jar:/usr/share/scilab/modules/scirenderer/jar/scirenderer.jar:/usr/share/scilab/modules/graphic_export/jar/org.scilab.modules.graphic_export.jar:/usr/share/scilab/modules/external_objects_java/jar/org.scilab.modules.external_objects_java.jar:/usr/share/scilab/modules/completion/jar/org.scilab.modules.completion.jar:/usr/share/scilab/modules/scinotes/jar/org.scilab.modules.scinotes.jar:/usr/share/scilab/modules/ui_data/jar/org.scilab.modules.ui_data.jar:/usr/share/scilab/modules/javasci/jar/org.scilab.modules.javasci.jar:/usr/share/scilab/modules/history_browser/jar/org.scilab.modules.history_browser.jar:/usr/share/scilab/modules/jvm/jar/org.scilab.modules.jvm.jar:/usr/share/scilab/modules/commons/jar/org.scilab.modules.commons.jar:/usr/share/scilab/modules/types/jar/org.scilab.modules.types.jar:/usr/share/scilab/modules/renderer/jar/org.scilab.modules.renderer.jar:/usr/share/scilab/modules/graphic_objects/jar/org.scilab.modules.graphic_objects.jar:/usr/share/scilab/modules/action_binding/jar/org.scilab.modules.action_binding.jar:/usr/share/scilab/modules/history_manager/jar/org.scilab.modules.history_manager.jar:/usr/share/scilab/modules/xcos/jar/org.scilab.modules.xcos.jar:/usr/share/scilab/modules/core/jar/org.scilab.modules.core.jar:/usr/share/scilab/modules/localization/jar/org.scilab.modules.localization.jar:/usr/share/scilab/modules/gui/jar/org.scilab.modules.gui.jar:/usr/share/scilab/modules/preferences/jar/org.scilab.modules.preferences.jar:/usr/share/scilab/modules/helptools/jar/scilab_en_US_help.jar:/usr/share/scilab/modules/helptools/jar/org.scilab.modules.helptools.jar:/usr/share/scilab/modules/helptools/jar/scilab_images.jar:/usr/share/scilab/modules/console/jar/org.scilab.modules.console.jar:  -Djava.library.path=/usr/lib/jni:/usr/lib/scilab --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED --add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
Could not load file: /usr/share/scilab//modules/preferences/src/xslt/XConfiguration.xsl
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.scilab.modules.gui.events.callback.JavaCallBack$2.callBack(Unknown Source)
        at org.scilab.modules.gui.events.callback.CommonCallBack.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.xml.transform.Transformer.transform(javax.xml.transform.Source, javax.xml.transform.Result)" because "org.scilab.modules.preferences.XCommonManager.transformer" is null
        at org.scilab.modules.preferences.XCommonManager.generateViewDOM(Unknown Source)
        at org.scilab.modules.preferences.XCommonManager.refreshDisplay(Unknown Source)
        at org.scilab.modules.preferences.XConfigManager.displayAndWait(Unknown Source)
        at org.scilab.modules.preferences.XConfigManager.openPreferences(Unknown Source)
        ... 42 more

**Comment by kevinsmia1939** [comment]
How about trying the Scilab binary from Scilab website? Does it have to same issue?
If Scilab only crash from the Debian repo, you should contact them instead.

**Comment by b606** [comment]
I wanted to test the flatpak version first before trying the original binary.

I would file a bug report to Debian repo as soon as possible about the java crash but the font problem seems to be originated somewhere in the font configuration of the Scilab UI engine. Oddly enough, some texts do not scale either in the Help Browser (using Ctrl-Mouse Scroll) .

`fc-list :mono | wc -l`  shows that I have 137 mono fonts installed (Noto, Hack, DejaVu, MS-ttf Courier etc...)

Thank you for the reply.

![Screenshot_20230713_215933](https://github.com/flathub/org.scilab.Scilab/assets/7627533/acc883e0-eb5d-4743-a691-6431a7e3c628)

**Comment by kevinsmia1939** [comment]
It would be faster to determine if it is flatpak fault if you test with binary first.

**Comment by b606** [comment]
The new binary from https://www.scilab.org/download/scilab-2023.1.0 has the same font problem.
Though, it reflects correctly the dasktop dark mode theme.

![Screenshot_20230714_084201](https://github.com/flathub/org.scilab.Scilab/assets/7627533/556ba2a1-d272-4247-a34f-7156f334d1e3)

**Comment by kevinsmia1939** [comment]
Then I think you should report this to Scilab bug report instead, I think I will close this now.

**Comment by b606** [comment]
Scilab bug report at https://gitlab.com/scilab/scilab/-/issues/17085
